# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from paycor_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from paycor_python_sdk.api_response import AsyncGeneratorResponse
from paycor_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401

from paycor_python_sdk.model.employee_exemptions import EmployeeExemptions as EmployeeExemptionsSchema
from paycor_python_sdk.model.employee_tax_credit import EmployeeTaxCredit as EmployeeTaxCreditSchema
from paycor_python_sdk.model.filing_status2 import FilingStatus2 as FilingStatus2Schema
from paycor_python_sdk.model.employee_tax3 import EmployeeTax3 as EmployeeTax3Schema
from paycor_python_sdk.model.employee_taxes_update_by_employee_id_response import EmployeeTaxesUpdateByEmployeeIdResponse as EmployeeTaxesUpdateByEmployeeIdResponseSchema
from paycor_python_sdk.model.paycor_error import PaycorError as PaycorErrorSchema
from paycor_python_sdk.model.reciprocity_type import ReciprocityType as ReciprocityTypeSchema

from paycor_python_sdk.type.employee_tax3 import EmployeeTax3
from paycor_python_sdk.type.filing_status2 import FilingStatus2
from paycor_python_sdk.type.employee_exemptions import EmployeeExemptions
from paycor_python_sdk.type.reciprocity_type import ReciprocityType
from paycor_python_sdk.type.paycor_error import PaycorError
from paycor_python_sdk.type.employee_tax_credit import EmployeeTaxCredit
from paycor_python_sdk.type.employee_taxes_update_by_employee_id_response import EmployeeTaxesUpdateByEmployeeIdResponse

from ...api_client import Dictionary
from paycor_python_sdk.pydantic.filing_status2 import FilingStatus2 as FilingStatus2Pydantic
from paycor_python_sdk.pydantic.employee_tax_credit import EmployeeTaxCredit as EmployeeTaxCreditPydantic
from paycor_python_sdk.pydantic.employee_taxes_update_by_employee_id_response import EmployeeTaxesUpdateByEmployeeIdResponse as EmployeeTaxesUpdateByEmployeeIdResponsePydantic
from paycor_python_sdk.pydantic.reciprocity_type import ReciprocityType as ReciprocityTypePydantic
from paycor_python_sdk.pydantic.employee_tax3 import EmployeeTax3 as EmployeeTax3Pydantic
from paycor_python_sdk.pydantic.paycor_error import PaycorError as PaycorErrorPydantic
from paycor_python_sdk.pydantic.employee_exemptions import EmployeeExemptions as EmployeeExemptionsPydantic

from . import path

# Path params
EmployeeIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'employeeId': typing.Union[EmployeeIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_employee_id = api_client.PathParameter(
    name="employeeId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=EmployeeIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = EmployeeTax3Schema


request_body_employee_tax3 = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'Access-Token',
    'Apim-Subscription-Key',
]
SchemaFor200ResponseBodyApplicationJson = EmployeeTaxesUpdateByEmployeeIdResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: EmployeeTaxesUpdateByEmployeeIdResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: EmployeeTaxesUpdateByEmployeeIdResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = PaycorErrorSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: PaycorError


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: PaycorError


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor500ResponseBodyApplicationJson = PaycorErrorSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: PaycorError


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: PaycorError


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '404': _response_for_404,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_by_employee_id_mapped_args(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if id is not None:
            _body["Id"] = id
        if legal_entity_tax_id is not None:
            _body["LegalEntityTaxId"] = legal_entity_tax_id
        if reciprocity_type is not None:
            _body["ReciprocityType"] = reciprocity_type
        if filing_status is not None:
            _body["FilingStatus"] = filing_status
        if withholding_effective_start_date is not None:
            _body["WithholdingEffectiveStartDate"] = withholding_effective_start_date
        if block_date is not None:
            _body["BlockDate"] = block_date
        if non_resident_alien is not None:
            _body["NonResidentAlien"] = non_resident_alien
        if is_probationary_employee is not None:
            _body["IsProbationaryEmployee"] = is_probationary_employee
        if occupational_code is not None:
            _body["OccupationalCode"] = occupational_code
        if geographic_code is not None:
            _body["GeographicCode"] = geographic_code
        if soc_code is not None:
            _body["SOCCode"] = soc_code
        if seasonal_code is not None:
            _body["SeasonalCode"] = seasonal_code
        if county_code is not None:
            _body["CountyCode"] = county_code
        if spouse_work is not None:
            _body["SpouseWork"] = spouse_work
        if dependent_insurance_eligible is not None:
            _body["DependentInsuranceEligible"] = dependent_insurance_eligible
        if dependent_insurance_eligible_date is not None:
            _body["DependentInsuranceEligibleDate"] = dependent_insurance_eligible_date
        if applicable_birthyear is not None:
            _body["ApplicableBirthyear"] = applicable_birthyear
        if amount is not None:
            _body["Amount"] = amount
        if percentage is not None:
            _body["Percentage"] = percentage
        if ncci_code is not None:
            _body["NCCICode"] = ncci_code
        if psd_code is not None:
            _body["PsdCode"] = psd_code
        if psd_rate is not None:
            _body["PsdRate"] = psd_rate
        if on_hold is not None:
            _body["OnHold"] = on_hold
        if exemptions is not None:
            _body["Exemptions"] = exemptions
        if tax_credit is not None:
            _body["TaxCredit"] = tax_credit
        args.body = _body
        if employee_id is not None:
            _path_params["employeeId"] = employee_id
        args.path = _path_params
        return args

    async def _aupdate_by_employee_id_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Update Tax by EmployeeID
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_employee_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/employees/{employeeId}/taxes',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_employee_tax3.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_by_employee_id_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Update Tax by EmployeeID
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_employee_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/employees/{employeeId}/taxes',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_employee_tax3.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdateByEmployeeIdRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_by_employee_id(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_by_employee_id_mapped_args(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
        )
        return await self._aupdate_by_employee_id_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def update_by_employee_id(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_by_employee_id_mapped_args(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
        )
        return self._update_by_employee_id_oapg(
            body=args.body,
            path_params=args.path,
        )

class UpdateByEmployeeId(BaseApi):

    async def aupdate_by_employee_id(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
        validate: bool = False,
        **kwargs,
    ) -> EmployeeTaxesUpdateByEmployeeIdResponsePydantic:
        raw_response = await self.raw.aupdate_by_employee_id(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
            **kwargs,
        )
        if validate:
            return RootModel[EmployeeTaxesUpdateByEmployeeIdResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(EmployeeTaxesUpdateByEmployeeIdResponsePydantic, raw_response.body)
    
    
    def update_by_employee_id(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
        validate: bool = False,
    ) -> EmployeeTaxesUpdateByEmployeeIdResponsePydantic:
        raw_response = self.raw.update_by_employee_id(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
        )
        if validate:
            return RootModel[EmployeeTaxesUpdateByEmployeeIdResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(EmployeeTaxesUpdateByEmployeeIdResponsePydantic, raw_response.body)


class ApiForput(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aput(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_by_employee_id_mapped_args(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
        )
        return await self._aupdate_by_employee_id_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def put(
        self,
        id: str,
        legal_entity_tax_id: str,
        employee_id: str,
        reciprocity_type: typing.Optional[ReciprocityType] = None,
        filing_status: typing.Optional[FilingStatus2] = None,
        withholding_effective_start_date: typing.Optional[typing.Optional[datetime]] = None,
        block_date: typing.Optional[typing.Optional[datetime]] = None,
        non_resident_alien: typing.Optional[typing.Optional[str]] = None,
        is_probationary_employee: typing.Optional[typing.Optional[bool]] = None,
        occupational_code: typing.Optional[typing.Optional[str]] = None,
        geographic_code: typing.Optional[typing.Optional[str]] = None,
        soc_code: typing.Optional[typing.Optional[str]] = None,
        seasonal_code: typing.Optional[typing.Optional[str]] = None,
        county_code: typing.Optional[typing.Optional[str]] = None,
        spouse_work: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible: typing.Optional[typing.Optional[str]] = None,
        dependent_insurance_eligible_date: typing.Optional[typing.Optional[datetime]] = None,
        applicable_birthyear: typing.Optional[typing.Optional[int]] = None,
        amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        percentage: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        ncci_code: typing.Optional[typing.Optional[str]] = None,
        psd_code: typing.Optional[typing.Optional[str]] = None,
        psd_rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = None,
        on_hold: typing.Optional[typing.Optional[bool]] = None,
        exemptions: typing.Optional[EmployeeExemptions] = None,
        tax_credit: typing.Optional[EmployeeTaxCredit] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_by_employee_id_mapped_args(
            id=id,
            legal_entity_tax_id=legal_entity_tax_id,
            employee_id=employee_id,
            reciprocity_type=reciprocity_type,
            filing_status=filing_status,
            withholding_effective_start_date=withholding_effective_start_date,
            block_date=block_date,
            non_resident_alien=non_resident_alien,
            is_probationary_employee=is_probationary_employee,
            occupational_code=occupational_code,
            geographic_code=geographic_code,
            soc_code=soc_code,
            seasonal_code=seasonal_code,
            county_code=county_code,
            spouse_work=spouse_work,
            dependent_insurance_eligible=dependent_insurance_eligible,
            dependent_insurance_eligible_date=dependent_insurance_eligible_date,
            applicable_birthyear=applicable_birthyear,
            amount=amount,
            percentage=percentage,
            ncci_code=ncci_code,
            psd_code=psd_code,
            psd_rate=psd_rate,
            on_hold=on_hold,
            exemptions=exemptions,
            tax_credit=tax_credit,
        )
        return self._update_by_employee_id_oapg(
            body=args.body,
            path_params=args.path,
        )

