# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paycor_python_sdk.type.job_department import JobDepartment
from paycor_python_sdk.type.job_location import JobLocation
from paycor_python_sdk.type.job_pay_range import JobPayRange
from paycor_python_sdk.type.job_priority import JobPriority
from paycor_python_sdk.type.job_remote_status import JobRemoteStatus
from paycor_python_sdk.type.job_status import JobStatus
from paycor_python_sdk.type.job_user import JobUser

class RequiredJob(TypedDict):
    pass

class OptionalJob(TypedDict, total=False):
    # Unique identifier of the Job in Paycor's system.
    Id: typing.Optional[str]

    # The ATS client ID.
    ATSAccountId: typing.Optional[str]

    # The job's human readable job number.
    Number: typing.Optional[str]

    # The job's name.
    Title: typing.Optional[str]

    # The job's description in HTML format.
    Description: typing.Optional[str]

    Status: JobStatus

    # The number of openings for the job.
    Openings: int

    Priority: JobPriority

    # If the job is confidential.
    Confidential: bool

    # If the job is an internal only job.
    Internal: bool

    # The targeted time to fill the job.
    TimeToFill: int

    RemoteStatus: JobRemoteStatus

    # The EEO (Equal Employment Opportunity) category specification for the job. Can be one of these values: Executive/Senior-Level Officials and Managers, First/Mid-Level Officials and Managers, Professionals, Technicians, Sales Workers, Administrative Support Workers, Craft Workers, Operatives, Laborers and Helpers, Service Workers.
    EeoCategory: typing.Optional[str]

    PayRange: JobPayRange

    ATSLocation: JobLocation

    ATSDepartment: JobDepartment

    # The hiring managers assigned to the job.
    HiringManagers: typing.Optional[typing.List[JobUser]]

    # The recruiters assigned to the job.
    Recruiters: typing.Optional[typing.List[JobUser]]

    # The team members assigned to the job.
    TeamMembers: typing.Optional[typing.List[JobUser]]

    # The executives assigned to the job.
    Executives: typing.Optional[typing.List[JobUser]]

    # The date when the job was activated.
    ActivatedDate: typing.Optional[datetime]

    # The date when the job was created.
    CreatedDate: datetime

    # The date when the job was last modified.
    ModifiedDate: datetime

    # Is the job posted to the company careers page.
    PostedToCareers: bool

    # Is the job posted to the free Indeed feed.
    PostedToIndeed: bool

    # Is the job posted to Smart Sourcing.
    PostedToSmartSourcing: bool

    # Is the job posted to the free LinkedIn.
    PostedToLinkedIn: bool

    # Is the job posted to the free ZipRecruiter feed.
    PostedToZipRecruiter: bool

    # Is the job posted to Gravity.             
    PostedToGravity: bool

class Job(RequiredJob, OptionalJob):
    pass
