# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paycor_python_sdk.type.employment_status import EmploymentStatus

class RequiredJobCosting(TypedDict):
    pass

class OptionalJobCosting(TypedDict, total=False):
    # Id of the Legal Entity.
    LegalEntityId: typing.Optional[str]

    # The paycheck date. Also referred to as Pay Date.
    CheckDate: typing.Optional[datetime]

    # Description of department Synonymous with OrganizationDescription
    DepartmentDescription: typing.Optional[str]

    # Numeric code of department  Synonymous with OrganizationCode
    DepartmentCode: typing.Optional[int]

    # Labor category code 1
    LaborCategory1Code: typing.Optional[int]

    # Labor code 1
    LaborCode1: typing.Optional[str]

    # Labor Code 1 ID
    LaborCode1Id: typing.Optional[str]

    # Description of labor category 1
    LaborCode1Description: typing.Optional[str]

    # Labor category code 1
    LaborCategory2Code: typing.Optional[int]

    # Labor code 2
    LaborCode2: typing.Optional[str]

    # Labor Code 2 ID
    LaborCode2Id: typing.Optional[str]

    # Description of labor category 1
    LaborCode2Description: typing.Optional[str]

    # Labor category code 3
    LaborCategory3Code: typing.Optional[int]

    # Labor code 3
    LaborCode3: typing.Optional[str]

    # Labor Code 3 ID
    LaborCode3Id: typing.Optional[str]

    # Description of labor category 3
    LaborCode3Description: typing.Optional[str]

    # Labor category code 4
    LaborCategory4Code: typing.Optional[int]

    # Labor code 4
    LaborCode4: typing.Optional[str]

    # Labor Code 4 ID
    LaborCode4Id: typing.Optional[str]

    # Description of labor category 4
    LaborCode4Description: typing.Optional[str]

    # Labor category code 5
    LaborCategory5Code: typing.Optional[int]

    # Labor code 5
    LaborCode5: typing.Optional[str]

    # Labor Code 5 ID
    LaborCode5Id: typing.Optional[str]

    # Description of labor category 5
    LaborCode5Description: typing.Optional[str]

    # Labor category code 6
    LaborCategory6Code: typing.Optional[int]

    # Labor code 6
    LaborCode6: typing.Optional[str]

    # Labor Code 6 ID
    LaborCode6Id: typing.Optional[str]

    # Description of labor category 6
    LaborCode6Description: typing.Optional[str]

    # Account number 
    GLAccountNumber: typing.Optional[str]

    # Account description 
    GLAccountDescription: typing.Optional[str]

    # Credited amount
    CreditAmount: typing.Optional[typing.Union[int, float]]

    # Credited amount
    DebitAmount: typing.Optional[typing.Union[int, float]]

    # Week number
    WeekNumber: int

    # Pay number
    PayNumber: int

    # File Date Month
    FileDateMonth: int

    # File date day
    FileDateDay: int

    # File date year
    FileDateYear: int

    # Unique identifier of the employee record in Paycor's system. Generated by Paycor.
    EmployeeId: typing.Optional[str]

    # Employee's organization description
    EmployeeDepartmentDescription: typing.Optional[str]

    # Employee's organization code
    EmployeeDepartmentCode: typing.Optional[int]

    # Employee's last name
    EmployeeLastName: typing.Optional[str]

    # Employee's first name
    EmployeeFirstName: typing.Optional[str]

    # Employee's middle name
    EmployeeMiddleName: typing.Optional[str]

    # Unique number of the employee in the tenant. Generated by Paycor.
    EmployeeNumber: typing.Optional[int]

    EmployeeStatus: EmploymentStatus

    # Check number.
    CheckNumber: typing.Optional[int]

    # Period start date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
    PeriodStartDate: datetime

    # Period end date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
    PeriodEndDate: datetime

class JobCosting(RequiredJobCosting, OptionalJobCosting):
    pass
