# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from paycor_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    EMPLOYEES = "Employees"
    EMPLOYEE_DIRECT_DEPOSITS = "Employee Direct Deposits"
    EMPLOYEE_TAXES = "Employee Taxes"
    LEGAL_ENTITY_WORK_LOCATIONS = "Legal Entity Work Locations"
    PERSONS = "Persons"
    EMPLOYEE_DEDUCTIONS = "Employee Deductions"
    EMPLOYEE_EARNINGS = "Employee Earnings"
    EMPLOYEE_PAY_STUBS = "Employee Pay Stubs"
    EMPLOYEE_LEGACY___PERFORM_TIME_SCHEDULES = "Employee (Legacy / Perform Time) Schedules"
    LEGAL_ENTITY_DEPARTMENTS = "Legal Entity Departments"
    APPLICANT_TRACKING_SYSTEM = "Applicant Tracking System"
    EMPLOYEE_CERTIFICATIONS = "Employee Certifications"
    EMPLOYEE_PAY_RATES = "Employee Pay Rates"
    TIME_OFF_REQUESTS = "Time Off Requests"
    LABOR_CODES = "Labor Codes"
    TENANTS = "Tenants"
    EMPLOYEE_CUSTOM_FIELDS = "Employee Custom Fields"
    EMPLOYEE_DOCUMENTS = "Employee Documents"
    EMPLOYEE_PAYROLL_HOURS = "Employee Payroll Hours"
    EMPLOYEE_I9_VERIFICATION = "Employee I9 Verification"
    EMPLOYEE_ONBOARDING = "Employee Onboarding"
    EMPLOYEE_TIME_CARD_PUNCHES = "Employee Time Card Punches"
    EMPLOYEE_TIME_OFF_ACCRUALS = "Employee Time Off Accruals"
    LEGAL_ENTITIES = "Legal Entities"
    LEGAL_ENTITY_CERTIFICATIONS = "Legal Entity Certifications"
    EMPLOYEE_EMERGENCY_CONTACT = "Employee Emergency Contact"
    EMPLOYEE_PAY_SCHEDULE = "Employee Pay Schedule"
    GENERAL_LEDGER = "General Ledger"
    GENERAL_LEDGER_JOB_COSTING = "General Ledger Job Costing"
    LABOR_CATEGORIES = "Labor Categories"
    LEGAL_ENTITY_DEDUCTIONS = "Legal Entity Deductions"
    LEGAL_ENTITY_EARNINGS = "Legal Entity Earnings"
    LEGAL_ENTITY_JOB_TITLES = "Legal Entity Job Titles"
    LEGAL_ENTITY_PAY_DATA = "Legal Entity Pay Data"
    LEGAL_ENTITY_PAY_GROUPS = "Legal Entity Pay Groups"
    LEGAL_ENTITY_PAYROLL_PROCESSING_DATA = "Legal Entity Payroll Processing Data"
    LEGAL_ENTITY_PAY_SCHEDULE = "Legal Entity Pay Schedule"
    LEGAL_ENTITY_ACTIVITY_TYPES = "Legal Entity Activity Types"
    LEGAL_ENTITY_SCHEDULE_GROUPS = "Legal Entity Schedule Groups"
    LEGAL_ENTITY_SERVICES = "Legal Entity Services"
    LEGAL_ENTITY_STATUS_REASON = "Legal Entity Status Reason"
    LEGAL_ENTITY_TAXES = " Legal Entity Taxes"
    LEGAL_ENTITY_TIME_OFF_TYPES = "Legal Entity Time Off Types"
    LEGAL_ENTITY_WORK_SITES = "Legal Entity Work Sites"
    EVENTS = "Events"
    LEGAL_ENTITY_TIME_DATA = "Legal Entity Time Data"
    JOB_TITLES = "Job Titles"
