# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class AccrualBalanceData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Accrual Balance Data represents the employees summarized accrual balance information.
            
    """


    class MetaOapg:
        required = {
            "AvailableBalance",
            "HoursUsedYTD",
            "TimeOffTypeDescription",
            "EmployeeId",
            "PlannerId",
            "HoursAddedYTD",
        }
        
        class properties:
            
            
            class EmployeeId(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'guid'
                    min_length = 1
            
            
            class PlannerId(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'guid'
                    min_length = 1
            
            
            class TimeOffTypeDescription(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            HoursAddedYTD = schemas.Float64Schema
            HoursUsedYTD = schemas.Float64Schema
            AvailableBalance = schemas.Float64Schema
            PayNumber = schemas.Int32Schema
            
            
            class PeriodEndDate(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'PeriodEndDate':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class TimeOffTypeCode(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'TimeOffTypeCode':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class PrintOption(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'PrintOption':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class PayrunTypesToInclude(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'PayrunTypesToInclude':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            PrintDelayinDays = schemas.Int32Schema
            
            
            class ShortfallOption(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ShortfallOption':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class PrintBalancePaystubOption(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'PrintBalancePaystubOption':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            StartingBalance = schemas.Float64Schema
            MaxEntitledBalance = schemas.Float64Schema
            RemainingEntitledBalance = schemas.Float64Schema
            __annotations__ = {
                "EmployeeId": EmployeeId,
                "PlannerId": PlannerId,
                "TimeOffTypeDescription": TimeOffTypeDescription,
                "HoursAddedYTD": HoursAddedYTD,
                "HoursUsedYTD": HoursUsedYTD,
                "AvailableBalance": AvailableBalance,
                "PayNumber": PayNumber,
                "PeriodEndDate": PeriodEndDate,
                "TimeOffTypeCode": TimeOffTypeCode,
                "PrintOption": PrintOption,
                "PayrunTypesToInclude": PayrunTypesToInclude,
                "PrintDelayinDays": PrintDelayinDays,
                "ShortfallOption": ShortfallOption,
                "PrintBalancePaystubOption": PrintBalancePaystubOption,
                "StartingBalance": StartingBalance,
                "MaxEntitledBalance": MaxEntitledBalance,
                "RemainingEntitledBalance": RemainingEntitledBalance,
            }
    
    AvailableBalance: MetaOapg.properties.AvailableBalance
    HoursUsedYTD: MetaOapg.properties.HoursUsedYTD
    TimeOffTypeDescription: MetaOapg.properties.TimeOffTypeDescription
    EmployeeId: MetaOapg.properties.EmployeeId
    PlannerId: MetaOapg.properties.PlannerId
    HoursAddedYTD: MetaOapg.properties.HoursAddedYTD
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeId"]) -> MetaOapg.properties.EmployeeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PlannerId"]) -> MetaOapg.properties.PlannerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TimeOffTypeDescription"]) -> MetaOapg.properties.TimeOffTypeDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["HoursAddedYTD"]) -> MetaOapg.properties.HoursAddedYTD: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["HoursUsedYTD"]) -> MetaOapg.properties.HoursUsedYTD: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AvailableBalance"]) -> MetaOapg.properties.AvailableBalance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PayNumber"]) -> MetaOapg.properties.PayNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PeriodEndDate"]) -> MetaOapg.properties.PeriodEndDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TimeOffTypeCode"]) -> MetaOapg.properties.TimeOffTypeCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PrintOption"]) -> MetaOapg.properties.PrintOption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PayrunTypesToInclude"]) -> MetaOapg.properties.PayrunTypesToInclude: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PrintDelayinDays"]) -> MetaOapg.properties.PrintDelayinDays: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ShortfallOption"]) -> MetaOapg.properties.ShortfallOption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PrintBalancePaystubOption"]) -> MetaOapg.properties.PrintBalancePaystubOption: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["StartingBalance"]) -> MetaOapg.properties.StartingBalance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MaxEntitledBalance"]) -> MetaOapg.properties.MaxEntitledBalance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RemainingEntitledBalance"]) -> MetaOapg.properties.RemainingEntitledBalance: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["EmployeeId", "PlannerId", "TimeOffTypeDescription", "HoursAddedYTD", "HoursUsedYTD", "AvailableBalance", "PayNumber", "PeriodEndDate", "TimeOffTypeCode", "PrintOption", "PayrunTypesToInclude", "PrintDelayinDays", "ShortfallOption", "PrintBalancePaystubOption", "StartingBalance", "MaxEntitledBalance", "RemainingEntitledBalance", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeId"]) -> MetaOapg.properties.EmployeeId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PlannerId"]) -> MetaOapg.properties.PlannerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TimeOffTypeDescription"]) -> MetaOapg.properties.TimeOffTypeDescription: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["HoursAddedYTD"]) -> MetaOapg.properties.HoursAddedYTD: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["HoursUsedYTD"]) -> MetaOapg.properties.HoursUsedYTD: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AvailableBalance"]) -> MetaOapg.properties.AvailableBalance: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PayNumber"]) -> typing.Union[MetaOapg.properties.PayNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PeriodEndDate"]) -> typing.Union[MetaOapg.properties.PeriodEndDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TimeOffTypeCode"]) -> typing.Union[MetaOapg.properties.TimeOffTypeCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PrintOption"]) -> typing.Union[MetaOapg.properties.PrintOption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PayrunTypesToInclude"]) -> typing.Union[MetaOapg.properties.PayrunTypesToInclude, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PrintDelayinDays"]) -> typing.Union[MetaOapg.properties.PrintDelayinDays, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ShortfallOption"]) -> typing.Union[MetaOapg.properties.ShortfallOption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PrintBalancePaystubOption"]) -> typing.Union[MetaOapg.properties.PrintBalancePaystubOption, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["StartingBalance"]) -> typing.Union[MetaOapg.properties.StartingBalance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MaxEntitledBalance"]) -> typing.Union[MetaOapg.properties.MaxEntitledBalance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RemainingEntitledBalance"]) -> typing.Union[MetaOapg.properties.RemainingEntitledBalance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["EmployeeId", "PlannerId", "TimeOffTypeDescription", "HoursAddedYTD", "HoursUsedYTD", "AvailableBalance", "PayNumber", "PeriodEndDate", "TimeOffTypeCode", "PrintOption", "PayrunTypesToInclude", "PrintDelayinDays", "ShortfallOption", "PrintBalancePaystubOption", "StartingBalance", "MaxEntitledBalance", "RemainingEntitledBalance", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        AvailableBalance: typing.Union[MetaOapg.properties.AvailableBalance, decimal.Decimal, int, float, ],
        HoursUsedYTD: typing.Union[MetaOapg.properties.HoursUsedYTD, decimal.Decimal, int, float, ],
        TimeOffTypeDescription: typing.Union[MetaOapg.properties.TimeOffTypeDescription, str, ],
        EmployeeId: typing.Union[MetaOapg.properties.EmployeeId, str, ],
        PlannerId: typing.Union[MetaOapg.properties.PlannerId, str, ],
        HoursAddedYTD: typing.Union[MetaOapg.properties.HoursAddedYTD, decimal.Decimal, int, float, ],
        PayNumber: typing.Union[MetaOapg.properties.PayNumber, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        PeriodEndDate: typing.Union[MetaOapg.properties.PeriodEndDate, None, str, datetime, schemas.Unset] = schemas.unset,
        TimeOffTypeCode: typing.Union[MetaOapg.properties.TimeOffTypeCode, None, str, schemas.Unset] = schemas.unset,
        PrintOption: typing.Union[MetaOapg.properties.PrintOption, None, str, schemas.Unset] = schemas.unset,
        PayrunTypesToInclude: typing.Union[MetaOapg.properties.PayrunTypesToInclude, None, str, schemas.Unset] = schemas.unset,
        PrintDelayinDays: typing.Union[MetaOapg.properties.PrintDelayinDays, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        ShortfallOption: typing.Union[MetaOapg.properties.ShortfallOption, None, str, schemas.Unset] = schemas.unset,
        PrintBalancePaystubOption: typing.Union[MetaOapg.properties.PrintBalancePaystubOption, None, str, schemas.Unset] = schemas.unset,
        StartingBalance: typing.Union[MetaOapg.properties.StartingBalance, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        MaxEntitledBalance: typing.Union[MetaOapg.properties.MaxEntitledBalance, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        RemainingEntitledBalance: typing.Union[MetaOapg.properties.RemainingEntitledBalance, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccrualBalanceData':
        return super().__new__(
            cls,
            *args,
            AvailableBalance=AvailableBalance,
            HoursUsedYTD=HoursUsedYTD,
            TimeOffTypeDescription=TimeOffTypeDescription,
            EmployeeId=EmployeeId,
            PlannerId=PlannerId,
            HoursAddedYTD=HoursAddedYTD,
            PayNumber=PayNumber,
            PeriodEndDate=PeriodEndDate,
            TimeOffTypeCode=TimeOffTypeCode,
            PrintOption=PrintOption,
            PayrunTypesToInclude=PayrunTypesToInclude,
            PrintDelayinDays=PrintDelayinDays,
            ShortfallOption=ShortfallOption,
            PrintBalancePaystubOption=PrintBalancePaystubOption,
            StartingBalance=StartingBalance,
            MaxEntitledBalance=MaxEntitledBalance,
            RemainingEntitledBalance=RemainingEntitledBalance,
            _configuration=_configuration,
            **kwargs,
        )
