# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class Job(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details about the Job.
    """


    class MetaOapg:
        
        class properties:
            
            
            class Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class ATSAccountId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ATSAccountId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Number(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Number':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Title(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Title':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def Status() -> typing.Type['JobStatus']:
                return JobStatus
            Openings = schemas.Int32Schema
        
            @staticmethod
            def Priority() -> typing.Type['JobPriority']:
                return JobPriority
            Confidential = schemas.BoolSchema
            Internal = schemas.BoolSchema
            TimeToFill = schemas.Int32Schema
        
            @staticmethod
            def RemoteStatus() -> typing.Type['JobRemoteStatus']:
                return JobRemoteStatus
            
            
            class EeoCategory(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EeoCategory':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def PayRange() -> typing.Type['JobPayRange']:
                return JobPayRange
        
            @staticmethod
            def ATSLocation() -> typing.Type['JobLocation']:
                return JobLocation
        
            @staticmethod
            def ATSDepartment() -> typing.Type['JobDepartment']:
                return JobDepartment
            
            
            class HiringManagers(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['JobUser']:
                        return JobUser
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'HiringManagers':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Recruiters(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['JobUser']:
                        return JobUser
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Recruiters':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class TeamMembers(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['JobUser']:
                        return JobUser
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'TeamMembers':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Executives(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['JobUser']:
                        return JobUser
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Executives':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class ActivatedDate(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ActivatedDate':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            CreatedDate = schemas.DateTimeSchema
            ModifiedDate = schemas.DateTimeSchema
            PostedToCareers = schemas.BoolSchema
            PostedToIndeed = schemas.BoolSchema
            PostedToSmartSourcing = schemas.BoolSchema
            PostedToLinkedIn = schemas.BoolSchema
            PostedToZipRecruiter = schemas.BoolSchema
            PostedToGravity = schemas.BoolSchema
            __annotations__ = {
                "Id": Id,
                "ATSAccountId": ATSAccountId,
                "Number": Number,
                "Title": Title,
                "Description": Description,
                "Status": Status,
                "Openings": Openings,
                "Priority": Priority,
                "Confidential": Confidential,
                "Internal": Internal,
                "TimeToFill": TimeToFill,
                "RemoteStatus": RemoteStatus,
                "EeoCategory": EeoCategory,
                "PayRange": PayRange,
                "ATSLocation": ATSLocation,
                "ATSDepartment": ATSDepartment,
                "HiringManagers": HiringManagers,
                "Recruiters": Recruiters,
                "TeamMembers": TeamMembers,
                "Executives": Executives,
                "ActivatedDate": ActivatedDate,
                "CreatedDate": CreatedDate,
                "ModifiedDate": ModifiedDate,
                "PostedToCareers": PostedToCareers,
                "PostedToIndeed": PostedToIndeed,
                "PostedToSmartSourcing": PostedToSmartSourcing,
                "PostedToLinkedIn": PostedToLinkedIn,
                "PostedToZipRecruiter": PostedToZipRecruiter,
                "PostedToGravity": PostedToGravity,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Id"]) -> MetaOapg.properties.Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ATSAccountId"]) -> MetaOapg.properties.ATSAccountId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Number"]) -> MetaOapg.properties.Number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Title"]) -> MetaOapg.properties.Title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Description"]) -> MetaOapg.properties.Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Status"]) -> 'JobStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Openings"]) -> MetaOapg.properties.Openings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Priority"]) -> 'JobPriority': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Confidential"]) -> MetaOapg.properties.Confidential: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Internal"]) -> MetaOapg.properties.Internal: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TimeToFill"]) -> MetaOapg.properties.TimeToFill: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RemoteStatus"]) -> 'JobRemoteStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EeoCategory"]) -> MetaOapg.properties.EeoCategory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PayRange"]) -> 'JobPayRange': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ATSLocation"]) -> 'JobLocation': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ATSDepartment"]) -> 'JobDepartment': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["HiringManagers"]) -> MetaOapg.properties.HiringManagers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Recruiters"]) -> MetaOapg.properties.Recruiters: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TeamMembers"]) -> MetaOapg.properties.TeamMembers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Executives"]) -> MetaOapg.properties.Executives: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ActivatedDate"]) -> MetaOapg.properties.ActivatedDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CreatedDate"]) -> MetaOapg.properties.CreatedDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ModifiedDate"]) -> MetaOapg.properties.ModifiedDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToCareers"]) -> MetaOapg.properties.PostedToCareers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToIndeed"]) -> MetaOapg.properties.PostedToIndeed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToSmartSourcing"]) -> MetaOapg.properties.PostedToSmartSourcing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToLinkedIn"]) -> MetaOapg.properties.PostedToLinkedIn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToZipRecruiter"]) -> MetaOapg.properties.PostedToZipRecruiter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostedToGravity"]) -> MetaOapg.properties.PostedToGravity: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Id", "ATSAccountId", "Number", "Title", "Description", "Status", "Openings", "Priority", "Confidential", "Internal", "TimeToFill", "RemoteStatus", "EeoCategory", "PayRange", "ATSLocation", "ATSDepartment", "HiringManagers", "Recruiters", "TeamMembers", "Executives", "ActivatedDate", "CreatedDate", "ModifiedDate", "PostedToCareers", "PostedToIndeed", "PostedToSmartSourcing", "PostedToLinkedIn", "PostedToZipRecruiter", "PostedToGravity", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Id"]) -> typing.Union[MetaOapg.properties.Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ATSAccountId"]) -> typing.Union[MetaOapg.properties.ATSAccountId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Number"]) -> typing.Union[MetaOapg.properties.Number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Title"]) -> typing.Union[MetaOapg.properties.Title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Description"]) -> typing.Union[MetaOapg.properties.Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Status"]) -> typing.Union['JobStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Openings"]) -> typing.Union[MetaOapg.properties.Openings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Priority"]) -> typing.Union['JobPriority', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Confidential"]) -> typing.Union[MetaOapg.properties.Confidential, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Internal"]) -> typing.Union[MetaOapg.properties.Internal, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TimeToFill"]) -> typing.Union[MetaOapg.properties.TimeToFill, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RemoteStatus"]) -> typing.Union['JobRemoteStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EeoCategory"]) -> typing.Union[MetaOapg.properties.EeoCategory, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PayRange"]) -> typing.Union['JobPayRange', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ATSLocation"]) -> typing.Union['JobLocation', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ATSDepartment"]) -> typing.Union['JobDepartment', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["HiringManagers"]) -> typing.Union[MetaOapg.properties.HiringManagers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Recruiters"]) -> typing.Union[MetaOapg.properties.Recruiters, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TeamMembers"]) -> typing.Union[MetaOapg.properties.TeamMembers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Executives"]) -> typing.Union[MetaOapg.properties.Executives, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ActivatedDate"]) -> typing.Union[MetaOapg.properties.ActivatedDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CreatedDate"]) -> typing.Union[MetaOapg.properties.CreatedDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ModifiedDate"]) -> typing.Union[MetaOapg.properties.ModifiedDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToCareers"]) -> typing.Union[MetaOapg.properties.PostedToCareers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToIndeed"]) -> typing.Union[MetaOapg.properties.PostedToIndeed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToSmartSourcing"]) -> typing.Union[MetaOapg.properties.PostedToSmartSourcing, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToLinkedIn"]) -> typing.Union[MetaOapg.properties.PostedToLinkedIn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToZipRecruiter"]) -> typing.Union[MetaOapg.properties.PostedToZipRecruiter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostedToGravity"]) -> typing.Union[MetaOapg.properties.PostedToGravity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Id", "ATSAccountId", "Number", "Title", "Description", "Status", "Openings", "Priority", "Confidential", "Internal", "TimeToFill", "RemoteStatus", "EeoCategory", "PayRange", "ATSLocation", "ATSDepartment", "HiringManagers", "Recruiters", "TeamMembers", "Executives", "ActivatedDate", "CreatedDate", "ModifiedDate", "PostedToCareers", "PostedToIndeed", "PostedToSmartSourcing", "PostedToLinkedIn", "PostedToZipRecruiter", "PostedToGravity", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Id: typing.Union[MetaOapg.properties.Id, None, str, schemas.Unset] = schemas.unset,
        ATSAccountId: typing.Union[MetaOapg.properties.ATSAccountId, None, str, schemas.Unset] = schemas.unset,
        Number: typing.Union[MetaOapg.properties.Number, None, str, schemas.Unset] = schemas.unset,
        Title: typing.Union[MetaOapg.properties.Title, None, str, schemas.Unset] = schemas.unset,
        Description: typing.Union[MetaOapg.properties.Description, None, str, schemas.Unset] = schemas.unset,
        Status: typing.Union['JobStatus', schemas.Unset] = schemas.unset,
        Openings: typing.Union[MetaOapg.properties.Openings, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        Priority: typing.Union['JobPriority', schemas.Unset] = schemas.unset,
        Confidential: typing.Union[MetaOapg.properties.Confidential, bool, schemas.Unset] = schemas.unset,
        Internal: typing.Union[MetaOapg.properties.Internal, bool, schemas.Unset] = schemas.unset,
        TimeToFill: typing.Union[MetaOapg.properties.TimeToFill, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        RemoteStatus: typing.Union['JobRemoteStatus', schemas.Unset] = schemas.unset,
        EeoCategory: typing.Union[MetaOapg.properties.EeoCategory, None, str, schemas.Unset] = schemas.unset,
        PayRange: typing.Union['JobPayRange', schemas.Unset] = schemas.unset,
        ATSLocation: typing.Union['JobLocation', schemas.Unset] = schemas.unset,
        ATSDepartment: typing.Union['JobDepartment', schemas.Unset] = schemas.unset,
        HiringManagers: typing.Union[MetaOapg.properties.HiringManagers, list, tuple, None, schemas.Unset] = schemas.unset,
        Recruiters: typing.Union[MetaOapg.properties.Recruiters, list, tuple, None, schemas.Unset] = schemas.unset,
        TeamMembers: typing.Union[MetaOapg.properties.TeamMembers, list, tuple, None, schemas.Unset] = schemas.unset,
        Executives: typing.Union[MetaOapg.properties.Executives, list, tuple, None, schemas.Unset] = schemas.unset,
        ActivatedDate: typing.Union[MetaOapg.properties.ActivatedDate, None, str, datetime, schemas.Unset] = schemas.unset,
        CreatedDate: typing.Union[MetaOapg.properties.CreatedDate, str, datetime, schemas.Unset] = schemas.unset,
        ModifiedDate: typing.Union[MetaOapg.properties.ModifiedDate, str, datetime, schemas.Unset] = schemas.unset,
        PostedToCareers: typing.Union[MetaOapg.properties.PostedToCareers, bool, schemas.Unset] = schemas.unset,
        PostedToIndeed: typing.Union[MetaOapg.properties.PostedToIndeed, bool, schemas.Unset] = schemas.unset,
        PostedToSmartSourcing: typing.Union[MetaOapg.properties.PostedToSmartSourcing, bool, schemas.Unset] = schemas.unset,
        PostedToLinkedIn: typing.Union[MetaOapg.properties.PostedToLinkedIn, bool, schemas.Unset] = schemas.unset,
        PostedToZipRecruiter: typing.Union[MetaOapg.properties.PostedToZipRecruiter, bool, schemas.Unset] = schemas.unset,
        PostedToGravity: typing.Union[MetaOapg.properties.PostedToGravity, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Job':
        return super().__new__(
            cls,
            *args,
            Id=Id,
            ATSAccountId=ATSAccountId,
            Number=Number,
            Title=Title,
            Description=Description,
            Status=Status,
            Openings=Openings,
            Priority=Priority,
            Confidential=Confidential,
            Internal=Internal,
            TimeToFill=TimeToFill,
            RemoteStatus=RemoteStatus,
            EeoCategory=EeoCategory,
            PayRange=PayRange,
            ATSLocation=ATSLocation,
            ATSDepartment=ATSDepartment,
            HiringManagers=HiringManagers,
            Recruiters=Recruiters,
            TeamMembers=TeamMembers,
            Executives=Executives,
            ActivatedDate=ActivatedDate,
            CreatedDate=CreatedDate,
            ModifiedDate=ModifiedDate,
            PostedToCareers=PostedToCareers,
            PostedToIndeed=PostedToIndeed,
            PostedToSmartSourcing=PostedToSmartSourcing,
            PostedToLinkedIn=PostedToLinkedIn,
            PostedToZipRecruiter=PostedToZipRecruiter,
            PostedToGravity=PostedToGravity,
            _configuration=_configuration,
            **kwargs,
        )

from paycor_python_sdk.model.job_department import JobDepartment
from paycor_python_sdk.model.job_location import JobLocation
from paycor_python_sdk.model.job_pay_range import JobPayRange
from paycor_python_sdk.model.job_priority import JobPriority
from paycor_python_sdk.model.job_remote_status import JobRemoteStatus
from paycor_python_sdk.model.job_status import JobStatus
from paycor_python_sdk.model.job_user import JobUser
