# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class JobCosting(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class LegalEntityId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LegalEntityId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class CheckDate(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'CheckDate':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class DepartmentDescription(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'DepartmentDescription':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class DepartmentCode(
                schemas.Int64Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int64'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'DepartmentCode':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory1Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory1Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode1(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode1':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode1Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode1Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode1Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode1Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory2Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory2Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode2(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode2':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode2Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode2Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode2Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode2Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory3Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory3Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode3(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode3':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode3Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode3Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode3Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode3Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory4Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory4Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode4(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode4':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode4Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode4Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode4Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode4Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory5Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory5Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode5(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode5':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode5Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode5Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode5Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode5Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCategory6Code(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCategory6Code':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode6(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode6':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode6Id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode6Id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LaborCode6Description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LaborCode6Description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class GLAccountNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'GLAccountNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class GLAccountDescription(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'GLAccountDescription':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class CreditAmount(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'decimal'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'CreditAmount':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class DebitAmount(
                schemas.NumberBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'decimal'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, float, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'DebitAmount':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            WeekNumber = schemas.Int32Schema
            PayNumber = schemas.Int32Schema
            FileDateMonth = schemas.Int32Schema
            FileDateDay = schemas.Int32Schema
            FileDateYear = schemas.Int32Schema
            
            
            class EmployeeId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'guid'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeDepartmentDescription(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeDepartmentDescription':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeDepartmentCode(
                schemas.Int64Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int64'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeDepartmentCode':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeLastName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeLastName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeFirstName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeFirstName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeMiddleName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeMiddleName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeNumber(
                schemas.Int32Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def EmployeeStatus() -> typing.Type['EmploymentStatus']:
                return EmploymentStatus
            
            
            class CheckNumber(
                schemas.Int64Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int64'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'CheckNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            PeriodStartDate = schemas.DateTimeSchema
            PeriodEndDate = schemas.DateTimeSchema
            __annotations__ = {
                "LegalEntityId": LegalEntityId,
                "CheckDate": CheckDate,
                "DepartmentDescription": DepartmentDescription,
                "DepartmentCode": DepartmentCode,
                "LaborCategory1Code": LaborCategory1Code,
                "LaborCode1": LaborCode1,
                "LaborCode1Id": LaborCode1Id,
                "LaborCode1Description": LaborCode1Description,
                "LaborCategory2Code": LaborCategory2Code,
                "LaborCode2": LaborCode2,
                "LaborCode2Id": LaborCode2Id,
                "LaborCode2Description": LaborCode2Description,
                "LaborCategory3Code": LaborCategory3Code,
                "LaborCode3": LaborCode3,
                "LaborCode3Id": LaborCode3Id,
                "LaborCode3Description": LaborCode3Description,
                "LaborCategory4Code": LaborCategory4Code,
                "LaborCode4": LaborCode4,
                "LaborCode4Id": LaborCode4Id,
                "LaborCode4Description": LaborCode4Description,
                "LaborCategory5Code": LaborCategory5Code,
                "LaborCode5": LaborCode5,
                "LaborCode5Id": LaborCode5Id,
                "LaborCode5Description": LaborCode5Description,
                "LaborCategory6Code": LaborCategory6Code,
                "LaborCode6": LaborCode6,
                "LaborCode6Id": LaborCode6Id,
                "LaborCode6Description": LaborCode6Description,
                "GLAccountNumber": GLAccountNumber,
                "GLAccountDescription": GLAccountDescription,
                "CreditAmount": CreditAmount,
                "DebitAmount": DebitAmount,
                "WeekNumber": WeekNumber,
                "PayNumber": PayNumber,
                "FileDateMonth": FileDateMonth,
                "FileDateDay": FileDateDay,
                "FileDateYear": FileDateYear,
                "EmployeeId": EmployeeId,
                "EmployeeDepartmentDescription": EmployeeDepartmentDescription,
                "EmployeeDepartmentCode": EmployeeDepartmentCode,
                "EmployeeLastName": EmployeeLastName,
                "EmployeeFirstName": EmployeeFirstName,
                "EmployeeMiddleName": EmployeeMiddleName,
                "EmployeeNumber": EmployeeNumber,
                "EmployeeStatus": EmployeeStatus,
                "CheckNumber": CheckNumber,
                "PeriodStartDate": PeriodStartDate,
                "PeriodEndDate": PeriodEndDate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LegalEntityId"]) -> MetaOapg.properties.LegalEntityId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CheckDate"]) -> MetaOapg.properties.CheckDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DepartmentDescription"]) -> MetaOapg.properties.DepartmentDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DepartmentCode"]) -> MetaOapg.properties.DepartmentCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory1Code"]) -> MetaOapg.properties.LaborCategory1Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode1"]) -> MetaOapg.properties.LaborCode1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode1Id"]) -> MetaOapg.properties.LaborCode1Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode1Description"]) -> MetaOapg.properties.LaborCode1Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory2Code"]) -> MetaOapg.properties.LaborCategory2Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode2"]) -> MetaOapg.properties.LaborCode2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode2Id"]) -> MetaOapg.properties.LaborCode2Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode2Description"]) -> MetaOapg.properties.LaborCode2Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory3Code"]) -> MetaOapg.properties.LaborCategory3Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode3"]) -> MetaOapg.properties.LaborCode3: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode3Id"]) -> MetaOapg.properties.LaborCode3Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode3Description"]) -> MetaOapg.properties.LaborCode3Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory4Code"]) -> MetaOapg.properties.LaborCategory4Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode4"]) -> MetaOapg.properties.LaborCode4: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode4Id"]) -> MetaOapg.properties.LaborCode4Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode4Description"]) -> MetaOapg.properties.LaborCode4Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory5Code"]) -> MetaOapg.properties.LaborCategory5Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode5"]) -> MetaOapg.properties.LaborCode5: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode5Id"]) -> MetaOapg.properties.LaborCode5Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode5Description"]) -> MetaOapg.properties.LaborCode5Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCategory6Code"]) -> MetaOapg.properties.LaborCategory6Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode6"]) -> MetaOapg.properties.LaborCode6: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode6Id"]) -> MetaOapg.properties.LaborCode6Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaborCode6Description"]) -> MetaOapg.properties.LaborCode6Description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["GLAccountNumber"]) -> MetaOapg.properties.GLAccountNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["GLAccountDescription"]) -> MetaOapg.properties.GLAccountDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CreditAmount"]) -> MetaOapg.properties.CreditAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DebitAmount"]) -> MetaOapg.properties.DebitAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["WeekNumber"]) -> MetaOapg.properties.WeekNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PayNumber"]) -> MetaOapg.properties.PayNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FileDateMonth"]) -> MetaOapg.properties.FileDateMonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FileDateDay"]) -> MetaOapg.properties.FileDateDay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FileDateYear"]) -> MetaOapg.properties.FileDateYear: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeId"]) -> MetaOapg.properties.EmployeeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeDepartmentDescription"]) -> MetaOapg.properties.EmployeeDepartmentDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeDepartmentCode"]) -> MetaOapg.properties.EmployeeDepartmentCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeLastName"]) -> MetaOapg.properties.EmployeeLastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeFirstName"]) -> MetaOapg.properties.EmployeeFirstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeMiddleName"]) -> MetaOapg.properties.EmployeeMiddleName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeNumber"]) -> MetaOapg.properties.EmployeeNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeStatus"]) -> 'EmploymentStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CheckNumber"]) -> MetaOapg.properties.CheckNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PeriodStartDate"]) -> MetaOapg.properties.PeriodStartDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PeriodEndDate"]) -> MetaOapg.properties.PeriodEndDate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["LegalEntityId", "CheckDate", "DepartmentDescription", "DepartmentCode", "LaborCategory1Code", "LaborCode1", "LaborCode1Id", "LaborCode1Description", "LaborCategory2Code", "LaborCode2", "LaborCode2Id", "LaborCode2Description", "LaborCategory3Code", "LaborCode3", "LaborCode3Id", "LaborCode3Description", "LaborCategory4Code", "LaborCode4", "LaborCode4Id", "LaborCode4Description", "LaborCategory5Code", "LaborCode5", "LaborCode5Id", "LaborCode5Description", "LaborCategory6Code", "LaborCode6", "LaborCode6Id", "LaborCode6Description", "GLAccountNumber", "GLAccountDescription", "CreditAmount", "DebitAmount", "WeekNumber", "PayNumber", "FileDateMonth", "FileDateDay", "FileDateYear", "EmployeeId", "EmployeeDepartmentDescription", "EmployeeDepartmentCode", "EmployeeLastName", "EmployeeFirstName", "EmployeeMiddleName", "EmployeeNumber", "EmployeeStatus", "CheckNumber", "PeriodStartDate", "PeriodEndDate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LegalEntityId"]) -> typing.Union[MetaOapg.properties.LegalEntityId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CheckDate"]) -> typing.Union[MetaOapg.properties.CheckDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DepartmentDescription"]) -> typing.Union[MetaOapg.properties.DepartmentDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DepartmentCode"]) -> typing.Union[MetaOapg.properties.DepartmentCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory1Code"]) -> typing.Union[MetaOapg.properties.LaborCategory1Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode1"]) -> typing.Union[MetaOapg.properties.LaborCode1, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode1Id"]) -> typing.Union[MetaOapg.properties.LaborCode1Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode1Description"]) -> typing.Union[MetaOapg.properties.LaborCode1Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory2Code"]) -> typing.Union[MetaOapg.properties.LaborCategory2Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode2"]) -> typing.Union[MetaOapg.properties.LaborCode2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode2Id"]) -> typing.Union[MetaOapg.properties.LaborCode2Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode2Description"]) -> typing.Union[MetaOapg.properties.LaborCode2Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory3Code"]) -> typing.Union[MetaOapg.properties.LaborCategory3Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode3"]) -> typing.Union[MetaOapg.properties.LaborCode3, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode3Id"]) -> typing.Union[MetaOapg.properties.LaborCode3Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode3Description"]) -> typing.Union[MetaOapg.properties.LaborCode3Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory4Code"]) -> typing.Union[MetaOapg.properties.LaborCategory4Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode4"]) -> typing.Union[MetaOapg.properties.LaborCode4, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode4Id"]) -> typing.Union[MetaOapg.properties.LaborCode4Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode4Description"]) -> typing.Union[MetaOapg.properties.LaborCode4Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory5Code"]) -> typing.Union[MetaOapg.properties.LaborCategory5Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode5"]) -> typing.Union[MetaOapg.properties.LaborCode5, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode5Id"]) -> typing.Union[MetaOapg.properties.LaborCode5Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode5Description"]) -> typing.Union[MetaOapg.properties.LaborCode5Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCategory6Code"]) -> typing.Union[MetaOapg.properties.LaborCategory6Code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode6"]) -> typing.Union[MetaOapg.properties.LaborCode6, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode6Id"]) -> typing.Union[MetaOapg.properties.LaborCode6Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaborCode6Description"]) -> typing.Union[MetaOapg.properties.LaborCode6Description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["GLAccountNumber"]) -> typing.Union[MetaOapg.properties.GLAccountNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["GLAccountDescription"]) -> typing.Union[MetaOapg.properties.GLAccountDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CreditAmount"]) -> typing.Union[MetaOapg.properties.CreditAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DebitAmount"]) -> typing.Union[MetaOapg.properties.DebitAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["WeekNumber"]) -> typing.Union[MetaOapg.properties.WeekNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PayNumber"]) -> typing.Union[MetaOapg.properties.PayNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FileDateMonth"]) -> typing.Union[MetaOapg.properties.FileDateMonth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FileDateDay"]) -> typing.Union[MetaOapg.properties.FileDateDay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FileDateYear"]) -> typing.Union[MetaOapg.properties.FileDateYear, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeId"]) -> typing.Union[MetaOapg.properties.EmployeeId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeDepartmentDescription"]) -> typing.Union[MetaOapg.properties.EmployeeDepartmentDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeDepartmentCode"]) -> typing.Union[MetaOapg.properties.EmployeeDepartmentCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeLastName"]) -> typing.Union[MetaOapg.properties.EmployeeLastName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeFirstName"]) -> typing.Union[MetaOapg.properties.EmployeeFirstName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeMiddleName"]) -> typing.Union[MetaOapg.properties.EmployeeMiddleName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeNumber"]) -> typing.Union[MetaOapg.properties.EmployeeNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeStatus"]) -> typing.Union['EmploymentStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CheckNumber"]) -> typing.Union[MetaOapg.properties.CheckNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PeriodStartDate"]) -> typing.Union[MetaOapg.properties.PeriodStartDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PeriodEndDate"]) -> typing.Union[MetaOapg.properties.PeriodEndDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["LegalEntityId", "CheckDate", "DepartmentDescription", "DepartmentCode", "LaborCategory1Code", "LaborCode1", "LaborCode1Id", "LaborCode1Description", "LaborCategory2Code", "LaborCode2", "LaborCode2Id", "LaborCode2Description", "LaborCategory3Code", "LaborCode3", "LaborCode3Id", "LaborCode3Description", "LaborCategory4Code", "LaborCode4", "LaborCode4Id", "LaborCode4Description", "LaborCategory5Code", "LaborCode5", "LaborCode5Id", "LaborCode5Description", "LaborCategory6Code", "LaborCode6", "LaborCode6Id", "LaborCode6Description", "GLAccountNumber", "GLAccountDescription", "CreditAmount", "DebitAmount", "WeekNumber", "PayNumber", "FileDateMonth", "FileDateDay", "FileDateYear", "EmployeeId", "EmployeeDepartmentDescription", "EmployeeDepartmentCode", "EmployeeLastName", "EmployeeFirstName", "EmployeeMiddleName", "EmployeeNumber", "EmployeeStatus", "CheckNumber", "PeriodStartDate", "PeriodEndDate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        LegalEntityId: typing.Union[MetaOapg.properties.LegalEntityId, None, str, schemas.Unset] = schemas.unset,
        CheckDate: typing.Union[MetaOapg.properties.CheckDate, None, str, datetime, schemas.Unset] = schemas.unset,
        DepartmentDescription: typing.Union[MetaOapg.properties.DepartmentDescription, None, str, schemas.Unset] = schemas.unset,
        DepartmentCode: typing.Union[MetaOapg.properties.DepartmentCode, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCategory1Code: typing.Union[MetaOapg.properties.LaborCategory1Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode1: typing.Union[MetaOapg.properties.LaborCode1, None, str, schemas.Unset] = schemas.unset,
        LaborCode1Id: typing.Union[MetaOapg.properties.LaborCode1Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode1Description: typing.Union[MetaOapg.properties.LaborCode1Description, None, str, schemas.Unset] = schemas.unset,
        LaborCategory2Code: typing.Union[MetaOapg.properties.LaborCategory2Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode2: typing.Union[MetaOapg.properties.LaborCode2, None, str, schemas.Unset] = schemas.unset,
        LaborCode2Id: typing.Union[MetaOapg.properties.LaborCode2Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode2Description: typing.Union[MetaOapg.properties.LaborCode2Description, None, str, schemas.Unset] = schemas.unset,
        LaborCategory3Code: typing.Union[MetaOapg.properties.LaborCategory3Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode3: typing.Union[MetaOapg.properties.LaborCode3, None, str, schemas.Unset] = schemas.unset,
        LaborCode3Id: typing.Union[MetaOapg.properties.LaborCode3Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode3Description: typing.Union[MetaOapg.properties.LaborCode3Description, None, str, schemas.Unset] = schemas.unset,
        LaborCategory4Code: typing.Union[MetaOapg.properties.LaborCategory4Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode4: typing.Union[MetaOapg.properties.LaborCode4, None, str, schemas.Unset] = schemas.unset,
        LaborCode4Id: typing.Union[MetaOapg.properties.LaborCode4Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode4Description: typing.Union[MetaOapg.properties.LaborCode4Description, None, str, schemas.Unset] = schemas.unset,
        LaborCategory5Code: typing.Union[MetaOapg.properties.LaborCategory5Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode5: typing.Union[MetaOapg.properties.LaborCode5, None, str, schemas.Unset] = schemas.unset,
        LaborCode5Id: typing.Union[MetaOapg.properties.LaborCode5Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode5Description: typing.Union[MetaOapg.properties.LaborCode5Description, None, str, schemas.Unset] = schemas.unset,
        LaborCategory6Code: typing.Union[MetaOapg.properties.LaborCategory6Code, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaborCode6: typing.Union[MetaOapg.properties.LaborCode6, None, str, schemas.Unset] = schemas.unset,
        LaborCode6Id: typing.Union[MetaOapg.properties.LaborCode6Id, None, str, schemas.Unset] = schemas.unset,
        LaborCode6Description: typing.Union[MetaOapg.properties.LaborCode6Description, None, str, schemas.Unset] = schemas.unset,
        GLAccountNumber: typing.Union[MetaOapg.properties.GLAccountNumber, None, str, schemas.Unset] = schemas.unset,
        GLAccountDescription: typing.Union[MetaOapg.properties.GLAccountDescription, None, str, schemas.Unset] = schemas.unset,
        CreditAmount: typing.Union[MetaOapg.properties.CreditAmount, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        DebitAmount: typing.Union[MetaOapg.properties.DebitAmount, None, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        WeekNumber: typing.Union[MetaOapg.properties.WeekNumber, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        PayNumber: typing.Union[MetaOapg.properties.PayNumber, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        FileDateMonth: typing.Union[MetaOapg.properties.FileDateMonth, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        FileDateDay: typing.Union[MetaOapg.properties.FileDateDay, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        FileDateYear: typing.Union[MetaOapg.properties.FileDateYear, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        EmployeeId: typing.Union[MetaOapg.properties.EmployeeId, None, str, schemas.Unset] = schemas.unset,
        EmployeeDepartmentDescription: typing.Union[MetaOapg.properties.EmployeeDepartmentDescription, None, str, schemas.Unset] = schemas.unset,
        EmployeeDepartmentCode: typing.Union[MetaOapg.properties.EmployeeDepartmentCode, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        EmployeeLastName: typing.Union[MetaOapg.properties.EmployeeLastName, None, str, schemas.Unset] = schemas.unset,
        EmployeeFirstName: typing.Union[MetaOapg.properties.EmployeeFirstName, None, str, schemas.Unset] = schemas.unset,
        EmployeeMiddleName: typing.Union[MetaOapg.properties.EmployeeMiddleName, None, str, schemas.Unset] = schemas.unset,
        EmployeeNumber: typing.Union[MetaOapg.properties.EmployeeNumber, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        EmployeeStatus: typing.Union['EmploymentStatus', schemas.Unset] = schemas.unset,
        CheckNumber: typing.Union[MetaOapg.properties.CheckNumber, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        PeriodStartDate: typing.Union[MetaOapg.properties.PeriodStartDate, str, datetime, schemas.Unset] = schemas.unset,
        PeriodEndDate: typing.Union[MetaOapg.properties.PeriodEndDate, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JobCosting':
        return super().__new__(
            cls,
            *args,
            LegalEntityId=LegalEntityId,
            CheckDate=CheckDate,
            DepartmentDescription=DepartmentDescription,
            DepartmentCode=DepartmentCode,
            LaborCategory1Code=LaborCategory1Code,
            LaborCode1=LaborCode1,
            LaborCode1Id=LaborCode1Id,
            LaborCode1Description=LaborCode1Description,
            LaborCategory2Code=LaborCategory2Code,
            LaborCode2=LaborCode2,
            LaborCode2Id=LaborCode2Id,
            LaborCode2Description=LaborCode2Description,
            LaborCategory3Code=LaborCategory3Code,
            LaborCode3=LaborCode3,
            LaborCode3Id=LaborCode3Id,
            LaborCode3Description=LaborCode3Description,
            LaborCategory4Code=LaborCategory4Code,
            LaborCode4=LaborCode4,
            LaborCode4Id=LaborCode4Id,
            LaborCode4Description=LaborCode4Description,
            LaborCategory5Code=LaborCategory5Code,
            LaborCode5=LaborCode5,
            LaborCode5Id=LaborCode5Id,
            LaborCode5Description=LaborCode5Description,
            LaborCategory6Code=LaborCategory6Code,
            LaborCode6=LaborCode6,
            LaborCode6Id=LaborCode6Id,
            LaborCode6Description=LaborCode6Description,
            GLAccountNumber=GLAccountNumber,
            GLAccountDescription=GLAccountDescription,
            CreditAmount=CreditAmount,
            DebitAmount=DebitAmount,
            WeekNumber=WeekNumber,
            PayNumber=PayNumber,
            FileDateMonth=FileDateMonth,
            FileDateDay=FileDateDay,
            FileDateYear=FileDateYear,
            EmployeeId=EmployeeId,
            EmployeeDepartmentDescription=EmployeeDepartmentDescription,
            EmployeeDepartmentCode=EmployeeDepartmentCode,
            EmployeeLastName=EmployeeLastName,
            EmployeeFirstName=EmployeeFirstName,
            EmployeeMiddleName=EmployeeMiddleName,
            EmployeeNumber=EmployeeNumber,
            EmployeeStatus=EmployeeStatus,
            CheckNumber=CheckNumber,
            PeriodStartDate=PeriodStartDate,
            PeriodEndDate=PeriodEndDate,
            _configuration=_configuration,
            **kwargs,
        )

from paycor_python_sdk.model.employment_status import EmploymentStatus
