# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class ListBDocument(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Enumeration of valid List B document values.
            
    """
    
    @schemas.classproperty
    def DRIVER_LICENSEOR_IDCARD(cls):
        return cls("DriverLicenseorIDcard")
    
    @schemas.classproperty
    def FEDERAL_ORSTATE_ORLOCAL_GOVT_ID(cls):
        return cls("FederalORstateORLocalGovtID")
    
    @schemas.classproperty
    def SCHOOL_IDCARD_WITH_PHOTOGRAPH(cls):
        return cls("SchoolIDcardWithPhotograph")
    
    @schemas.classproperty
    def VOTERS_REGISTRATION_CARD(cls):
        return cls("VotersRegistrationCard")
    
    @schemas.classproperty
    def USMILITARY_CARD_OR_DRAFT_RECORD(cls):
        return cls("USMilitaryCardOrDraftRecord")
    
    @schemas.classproperty
    def MILITARY_DEPENDENTS_IDCARD(cls):
        return cls("MilitaryDependentsIDcard")
    
    @schemas.classproperty
    def USCOAST_GUARD_MERCHANT_MARINER(cls):
        return cls("USCoastGuardMerchantMariner")
    
    @schemas.classproperty
    def NATIVE_AMERICAN_TRIBAL_DOC(cls):
        return cls("NativeAmericanTribalDoc")
    
    @schemas.classproperty
    def DRIVER_LICENSE_CANADIAN_GOVT(cls):
        return cls("DriverLicenseCanadianGovt")
    
    @schemas.classproperty
    def SCHOOL_RECORD_OR_REPORT_CARD(cls):
        return cls("SchoolRecordOrReportCard")
    
    @schemas.classproperty
    def CLINIC_DOCTOR_OR_HOSPITAL_RECORD(cls):
        return cls("ClinicDoctorOrHospitalRecord")
    
    @schemas.classproperty
    def DAYCARE_OR_NURSERY_SCHOOL_RECORD(cls):
        return cls("DaycareOrNurserySchoolRecord")
    
    @schemas.classproperty
    def DRIVER_LICENSE(cls):
        return cls("DriverLicense")
    
    @schemas.classproperty
    def IDCARD_ISSUED_BY_USSTATE_OR_OUTLYING_POSSESSION(cls):
        return cls("IDCardIssuedByUSStateOrOutlyingPossession")
    
    @schemas.classproperty
    def RECEIPT_DRIVER_LICENSE_OR_IDCARD(cls):
        return cls("ReceiptDriverLicenseOrIDCard")
    
    @schemas.classproperty
    def RECEIPT_FEDERAL_OR_STATE_OR_LOCAL_GOVT_ID(cls):
        return cls("ReceiptFederalOrStateOrLocalGovtID")
    
    @schemas.classproperty
    def RECEIPT_SCHOOL_IDCARD_WITH_PHOTOGRAPH(cls):
        return cls("ReceiptSchoolIDCardWithPhotograph")
    
    @schemas.classproperty
    def RECEIPT_VOTERS_REGISTRATION_CARD(cls):
        return cls("ReceiptVotersRegistrationCard")
    
    @schemas.classproperty
    def RECEIPT_USMILITARY_CARD_OR_DRAFT_RECORD(cls):
        return cls("ReceiptUSMilitaryCardOrDraftRecord")
    
    @schemas.classproperty
    def RECEIPT_MILITARY_DEPENDENTS_IDCARD(cls):
        return cls("ReceiptMilitaryDependentsIDCard")
    
    @schemas.classproperty
    def RECEIPT_USCOAST_GUARD_MERCHANT_MARINER(cls):
        return cls("ReceiptUSCoastGuardMerchantMariner")
    
    @schemas.classproperty
    def RECEIPT_NATIVE_AMERICAN_TRIBAL_DOC(cls):
        return cls("ReceiptNativeAmericanTribalDoc")
    
    @schemas.classproperty
    def RECEIPT_DRIVER_LICENSE_CANADIAN_GOVT(cls):
        return cls("ReceiptDriverLicenseCanadianGovt")
    
    @schemas.classproperty
    def RECEIPT_SCHOOL_RECORD_OR_REPORT_CARD(cls):
        return cls("ReceiptSchoolRecordOrReportCard")
    
    @schemas.classproperty
    def RECEIPT_CLINIC_DOCTOR_OR_HOSPITAL_RECORD(cls):
        return cls("ReceiptClinicDoctorOrHospitalRecord")
    
    @schemas.classproperty
    def RECEIPT_DAY_CARE_OR_NURSERY_SCHOOL_RECORD(cls):
        return cls("ReceiptDayCareOrNurserySchoolRecord")
    
    @schemas.classproperty
    def RECEIPT_DRIVERS_LICENSE(cls):
        return cls("ReceiptDriversLicense")
    
    @schemas.classproperty
    def RECEIPT_USSTATE_CARD_OR_OUTLYING_POSSESSION(cls):
        return cls("ReceiptUSStateCardOrOutlyingPossession")
