# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class ListCDocument(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Enumeration of valid List C document values.
            
    """


    class MetaOapg:
        enum_value_to_name = {
            "SocialSecurityAccountNumber": "SOCIAL_SECURITY_ACCOUNT_NUMBER",
            "CertificateOfBirthDS1350orFS545FS240": "CERTIFICATE_OF_BIRTH_DS1350OR_FS545FS240",
            "CertificationOfBirthAbroadFS545": "CERTIFICATION_OF_BIRTH_ABROAD_FS545",
            "CertificateOfReportOfBirthDS1350": "CERTIFICATE_OF_REPORT_OF_BIRTH_DS1350",
            "ConsularReportOfBirthAbroadFS240": "CONSULAR_REPORT_OF_BIRTH_ABROAD_FS240",
            "USBirthCertificate": "USBIRTH_CERTIFICATE",
            "NativeAmericanTribalDoc": "NATIVE_AMERICAN_TRIBAL_DOC",
            "USCitizenIDCardI197": "USCITIZEN_IDCARD_I197",
            "IDCardForResidentCitizenI179": "IDCARD_FOR_RESIDENT_CITIZEN_I179",
            "EmploymentAuthorisationDocumentDHS": "EMPLOYMENT_AUTHORISATION_DOCUMENT_DHS",
            "ReceiptSocialSecurityAccountNumber": "RECEIPT_SOCIAL_SECURITY_ACCOUNT_NUMBER",
            "ReceiptUSBirthCertificate": "RECEIPT_USBIRTH_CERTIFICATE",
            "ReceiptNativeAmericanTribalDoc": "RECEIPT_NATIVE_AMERICAN_TRIBAL_DOC",
            "ReceiptUSCitizenIDCardI197": "RECEIPT_USCITIZEN_IDCARD_I197",
            "ReceiptIDCardForResidentCitizenI179": "RECEIPT_IDCARD_FOR_RESIDENT_CITIZEN_I179",
            "ReceiptEmploymentAuthorizationDocumentDHS": "RECEIPT_EMPLOYMENT_AUTHORIZATION_DOCUMENT_DHS",
            "CertificationOfBirthDS1350FS545FS240": "CERTIFICATION_OF_BIRTH_DS1350FS545FS240",
            "ReceiptCertificationOfBirthAbroadFS545": "RECEIPT_CERTIFICATION_OF_BIRTH_ABROAD_FS545",
            "ReceiptCertificateOfReportOfBirthDS1350": "RECEIPT_CERTIFICATE_OF_REPORT_OF_BIRTH_DS1350",
            "ReceiptConsularReportOfBirthAbroadFS240": "RECEIPT_CONSULAR_REPORT_OF_BIRTH_ABROAD_FS240",
        }
    
    @schemas.classproperty
    def SOCIAL_SECURITY_ACCOUNT_NUMBER(cls):
        return cls("SocialSecurityAccountNumber")
    
    @schemas.classproperty
    def CERTIFICATE_OF_BIRTH_DS1350OR_FS545FS240(cls):
        return cls("CertificateOfBirthDS1350orFS545FS240")
    
    @schemas.classproperty
    def CERTIFICATION_OF_BIRTH_ABROAD_FS545(cls):
        return cls("CertificationOfBirthAbroadFS545")
    
    @schemas.classproperty
    def CERTIFICATE_OF_REPORT_OF_BIRTH_DS1350(cls):
        return cls("CertificateOfReportOfBirthDS1350")
    
    @schemas.classproperty
    def CONSULAR_REPORT_OF_BIRTH_ABROAD_FS240(cls):
        return cls("ConsularReportOfBirthAbroadFS240")
    
    @schemas.classproperty
    def USBIRTH_CERTIFICATE(cls):
        return cls("USBirthCertificate")
    
    @schemas.classproperty
    def NATIVE_AMERICAN_TRIBAL_DOC(cls):
        return cls("NativeAmericanTribalDoc")
    
    @schemas.classproperty
    def USCITIZEN_IDCARD_I197(cls):
        return cls("USCitizenIDCardI197")
    
    @schemas.classproperty
    def IDCARD_FOR_RESIDENT_CITIZEN_I179(cls):
        return cls("IDCardForResidentCitizenI179")
    
    @schemas.classproperty
    def EMPLOYMENT_AUTHORISATION_DOCUMENT_DHS(cls):
        return cls("EmploymentAuthorisationDocumentDHS")
    
    @schemas.classproperty
    def RECEIPT_SOCIAL_SECURITY_ACCOUNT_NUMBER(cls):
        return cls("ReceiptSocialSecurityAccountNumber")
    
    @schemas.classproperty
    def RECEIPT_USBIRTH_CERTIFICATE(cls):
        return cls("ReceiptUSBirthCertificate")
    
    @schemas.classproperty
    def RECEIPT_NATIVE_AMERICAN_TRIBAL_DOC(cls):
        return cls("ReceiptNativeAmericanTribalDoc")
    
    @schemas.classproperty
    def RECEIPT_USCITIZEN_IDCARD_I197(cls):
        return cls("ReceiptUSCitizenIDCardI197")
    
    @schemas.classproperty
    def RECEIPT_IDCARD_FOR_RESIDENT_CITIZEN_I179(cls):
        return cls("ReceiptIDCardForResidentCitizenI179")
    
    @schemas.classproperty
    def RECEIPT_EMPLOYMENT_AUTHORIZATION_DOCUMENT_DHS(cls):
        return cls("ReceiptEmploymentAuthorizationDocumentDHS")
    
    @schemas.classproperty
    def CERTIFICATION_OF_BIRTH_DS1350FS545FS240(cls):
        return cls("CertificationOfBirthDS1350FS545FS240")
    
    @schemas.classproperty
    def RECEIPT_CERTIFICATION_OF_BIRTH_ABROAD_FS545(cls):
        return cls("ReceiptCertificationOfBirthAbroadFS545")
    
    @schemas.classproperty
    def RECEIPT_CERTIFICATE_OF_REPORT_OF_BIRTH_DS1350(cls):
        return cls("ReceiptCertificateOfReportOfBirthDS1350")
    
    @schemas.classproperty
    def RECEIPT_CONSULAR_REPORT_OF_BIRTH_ABROAD_FS240(cls):
        return cls("ReceiptConsularReportOfBirthAbroadFS240")
