# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paycor_python_sdk import schemas  # noqa: F401


class Person(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Each Person is associated with one or more Employees within one Tenant. An Employee works for a single Legal Entity within the Tenant.  If a person works
for multiple Legal Entities within a Tenant, they will be associated with multiple Employee records - but will only have a single Person record in the Paycor system.
Provides links to the Person's associated Employee, Legal Entity and Tenant information.
            
    """


    class MetaOapg:
        
        class properties:
            Id = schemas.StrSchema
        
            @staticmethod
            def Prefix() -> typing.Type['Prefix']:
                return Prefix
            
            
            class FirstName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'FirstName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class MiddleName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'MiddleName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LastName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LastName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def Suffix() -> typing.Type['Suffix']:
                return Suffix
            
            
            class LegalFirstName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LegalFirstName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class LegalLastName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'LegalLastName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class SocialSecurityNumber(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'SocialSecurityNumber':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def Email() -> typing.Type['PersonEmail']:
                return PersonEmail
        
            @staticmethod
            def DemographicData() -> typing.Type['DemographicData']:
                return DemographicData
        
            @staticmethod
            def BenefitData() -> typing.Type['BenefitData']:
                return BenefitData
            
            
            class EmergencyContactData(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EmergencyContactData']:
                        return EmergencyContactData
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmergencyContactData':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def MilitaryData() -> typing.Type['MilitaryData']:
                return MilitaryData
            
            
            class SocialMediaData(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SocialMediaData']:
                        return SocialMediaData
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'SocialMediaData':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class EmployeeAssignments(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['EmployeeAssignment']:
                        return EmployeeAssignment
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'EmployeeAssignments':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Addresses(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PersonAddress']:
                        return PersonAddress
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Addresses':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class Phones(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Phone']:
                        return Phone
            
            
                def __new__(
                    cls,
                    *args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Phones':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def Tenants() -> typing.Type['ResourceReference']:
                return ResourceReference
            __annotations__ = {
                "Id": Id,
                "Prefix": Prefix,
                "FirstName": FirstName,
                "MiddleName": MiddleName,
                "LastName": LastName,
                "Suffix": Suffix,
                "LegalFirstName": LegalFirstName,
                "LegalLastName": LegalLastName,
                "SocialSecurityNumber": SocialSecurityNumber,
                "Email": Email,
                "DemographicData": DemographicData,
                "BenefitData": BenefitData,
                "EmergencyContactData": EmergencyContactData,
                "MilitaryData": MilitaryData,
                "SocialMediaData": SocialMediaData,
                "EmployeeAssignments": EmployeeAssignments,
                "Addresses": Addresses,
                "Phones": Phones,
                "Tenants": Tenants,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Id"]) -> MetaOapg.properties.Id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Prefix"]) -> 'Prefix': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FirstName"]) -> MetaOapg.properties.FirstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MiddleName"]) -> MetaOapg.properties.MiddleName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LastName"]) -> MetaOapg.properties.LastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Suffix"]) -> 'Suffix': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LegalFirstName"]) -> MetaOapg.properties.LegalFirstName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LegalLastName"]) -> MetaOapg.properties.LegalLastName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SocialSecurityNumber"]) -> MetaOapg.properties.SocialSecurityNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Email"]) -> 'PersonEmail': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DemographicData"]) -> 'DemographicData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BenefitData"]) -> 'BenefitData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmergencyContactData"]) -> MetaOapg.properties.EmergencyContactData: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["MilitaryData"]) -> 'MilitaryData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SocialMediaData"]) -> MetaOapg.properties.SocialMediaData: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["EmployeeAssignments"]) -> MetaOapg.properties.EmployeeAssignments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Addresses"]) -> MetaOapg.properties.Addresses: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Phones"]) -> MetaOapg.properties.Phones: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Tenants"]) -> 'ResourceReference': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Id", "Prefix", "FirstName", "MiddleName", "LastName", "Suffix", "LegalFirstName", "LegalLastName", "SocialSecurityNumber", "Email", "DemographicData", "BenefitData", "EmergencyContactData", "MilitaryData", "SocialMediaData", "EmployeeAssignments", "Addresses", "Phones", "Tenants", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Id"]) -> typing.Union[MetaOapg.properties.Id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Prefix"]) -> typing.Union['Prefix', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FirstName"]) -> typing.Union[MetaOapg.properties.FirstName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MiddleName"]) -> typing.Union[MetaOapg.properties.MiddleName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LastName"]) -> typing.Union[MetaOapg.properties.LastName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Suffix"]) -> typing.Union['Suffix', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LegalFirstName"]) -> typing.Union[MetaOapg.properties.LegalFirstName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LegalLastName"]) -> typing.Union[MetaOapg.properties.LegalLastName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SocialSecurityNumber"]) -> typing.Union[MetaOapg.properties.SocialSecurityNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Email"]) -> typing.Union['PersonEmail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DemographicData"]) -> typing.Union['DemographicData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BenefitData"]) -> typing.Union['BenefitData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmergencyContactData"]) -> typing.Union[MetaOapg.properties.EmergencyContactData, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["MilitaryData"]) -> typing.Union['MilitaryData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SocialMediaData"]) -> typing.Union[MetaOapg.properties.SocialMediaData, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["EmployeeAssignments"]) -> typing.Union[MetaOapg.properties.EmployeeAssignments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Addresses"]) -> typing.Union[MetaOapg.properties.Addresses, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Phones"]) -> typing.Union[MetaOapg.properties.Phones, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Tenants"]) -> typing.Union['ResourceReference', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Id", "Prefix", "FirstName", "MiddleName", "LastName", "Suffix", "LegalFirstName", "LegalLastName", "SocialSecurityNumber", "Email", "DemographicData", "BenefitData", "EmergencyContactData", "MilitaryData", "SocialMediaData", "EmployeeAssignments", "Addresses", "Phones", "Tenants", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Id: typing.Union[MetaOapg.properties.Id, str, schemas.Unset] = schemas.unset,
        Prefix: typing.Union['Prefix', schemas.Unset] = schemas.unset,
        FirstName: typing.Union[MetaOapg.properties.FirstName, None, str, schemas.Unset] = schemas.unset,
        MiddleName: typing.Union[MetaOapg.properties.MiddleName, None, str, schemas.Unset] = schemas.unset,
        LastName: typing.Union[MetaOapg.properties.LastName, None, str, schemas.Unset] = schemas.unset,
        Suffix: typing.Union['Suffix', schemas.Unset] = schemas.unset,
        LegalFirstName: typing.Union[MetaOapg.properties.LegalFirstName, None, str, schemas.Unset] = schemas.unset,
        LegalLastName: typing.Union[MetaOapg.properties.LegalLastName, None, str, schemas.Unset] = schemas.unset,
        SocialSecurityNumber: typing.Union[MetaOapg.properties.SocialSecurityNumber, None, str, schemas.Unset] = schemas.unset,
        Email: typing.Union['PersonEmail', schemas.Unset] = schemas.unset,
        DemographicData: typing.Union['DemographicData', schemas.Unset] = schemas.unset,
        BenefitData: typing.Union['BenefitData', schemas.Unset] = schemas.unset,
        EmergencyContactData: typing.Union[MetaOapg.properties.EmergencyContactData, list, tuple, None, schemas.Unset] = schemas.unset,
        MilitaryData: typing.Union['MilitaryData', schemas.Unset] = schemas.unset,
        SocialMediaData: typing.Union[MetaOapg.properties.SocialMediaData, list, tuple, None, schemas.Unset] = schemas.unset,
        EmployeeAssignments: typing.Union[MetaOapg.properties.EmployeeAssignments, list, tuple, None, schemas.Unset] = schemas.unset,
        Addresses: typing.Union[MetaOapg.properties.Addresses, list, tuple, None, schemas.Unset] = schemas.unset,
        Phones: typing.Union[MetaOapg.properties.Phones, list, tuple, None, schemas.Unset] = schemas.unset,
        Tenants: typing.Union['ResourceReference', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Person':
        return super().__new__(
            cls,
            *args,
            Id=Id,
            Prefix=Prefix,
            FirstName=FirstName,
            MiddleName=MiddleName,
            LastName=LastName,
            Suffix=Suffix,
            LegalFirstName=LegalFirstName,
            LegalLastName=LegalLastName,
            SocialSecurityNumber=SocialSecurityNumber,
            Email=Email,
            DemographicData=DemographicData,
            BenefitData=BenefitData,
            EmergencyContactData=EmergencyContactData,
            MilitaryData=MilitaryData,
            SocialMediaData=SocialMediaData,
            EmployeeAssignments=EmployeeAssignments,
            Addresses=Addresses,
            Phones=Phones,
            Tenants=Tenants,
            _configuration=_configuration,
            **kwargs,
        )

from paycor_python_sdk.model.benefit_data import BenefitData
from paycor_python_sdk.model.demographic_data import DemographicData
from paycor_python_sdk.model.emergency_contact_data import EmergencyContactData
from paycor_python_sdk.model.employee_assignment import EmployeeAssignment
from paycor_python_sdk.model.military_data import MilitaryData
from paycor_python_sdk.model.person_address import PersonAddress
from paycor_python_sdk.model.person_email import PersonEmail
from paycor_python_sdk.model.phone import Phone
from paycor_python_sdk.model.prefix import Prefix
from paycor_python_sdk.model.resource_reference import ResourceReference
from paycor_python_sdk.model.social_media_data import SocialMediaData
from paycor_python_sdk.model.suffix import Suffix
