# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paycor_python_sdk.pydantic.employment_status import EmploymentStatus

class JobCosting(BaseModel):
    # Id of the Legal Entity.
    legal_entity_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LegalEntityId')

    # The paycheck date. Also referred to as Pay Date.
    check_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='CheckDate')

    # Description of department Synonymous with OrganizationDescription
    department_description: typing.Optional[typing.Optional[str]] = Field(None, alias='DepartmentDescription')

    # Numeric code of department  Synonymous with OrganizationCode
    department_code: typing.Optional[typing.Optional[int]] = Field(None, alias='DepartmentCode')

    # Labor category code 1
    labor_category1_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory1Code')

    # Labor code 1
    labor_code1: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode1')

    # Labor Code 1 ID
    labor_code1_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode1Id')

    # Description of labor category 1
    labor_code1_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode1Description')

    # Labor category code 1
    labor_category2_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory2Code')

    # Labor code 2
    labor_code2: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode2')

    # Labor Code 2 ID
    labor_code2_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode2Id')

    # Description of labor category 1
    labor_code2_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode2Description')

    # Labor category code 3
    labor_category3_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory3Code')

    # Labor code 3
    labor_code3: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode3')

    # Labor Code 3 ID
    labor_code3_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode3Id')

    # Description of labor category 3
    labor_code3_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode3Description')

    # Labor category code 4
    labor_category4_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory4Code')

    # Labor code 4
    labor_code4: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode4')

    # Labor Code 4 ID
    labor_code4_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode4Id')

    # Description of labor category 4
    labor_code4_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode4Description')

    # Labor category code 5
    labor_category5_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory5Code')

    # Labor code 5
    labor_code5: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode5')

    # Labor Code 5 ID
    labor_code5_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode5Id')

    # Description of labor category 5
    labor_code5_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode5Description')

    # Labor category code 6
    labor_category6_code: typing.Optional[typing.Optional[int]] = Field(None, alias='LaborCategory6Code')

    # Labor code 6
    labor_code6: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode6')

    # Labor Code 6 ID
    labor_code6_id: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode6Id')

    # Description of labor category 6
    labor_code6_description: typing.Optional[typing.Optional[str]] = Field(None, alias='LaborCode6Description')

    # Account number 
    g_l_account_number: typing.Optional[typing.Optional[str]] = Field(None, alias='GLAccountNumber')

    # Account description 
    g_l_account_description: typing.Optional[typing.Optional[str]] = Field(None, alias='GLAccountDescription')

    # Credited amount
    credit_amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='CreditAmount')

    # Credited amount
    debit_amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='DebitAmount')

    # Week number
    week_number: typing.Optional[int] = Field(None, alias='WeekNumber')

    # Pay number
    pay_number: typing.Optional[int] = Field(None, alias='PayNumber')

    # File Date Month
    file_date_month: typing.Optional[int] = Field(None, alias='FileDateMonth')

    # File date day
    file_date_day: typing.Optional[int] = Field(None, alias='FileDateDay')

    # File date year
    file_date_year: typing.Optional[int] = Field(None, alias='FileDateYear')

    # Unique identifier of the employee record in Paycor's system. Generated by Paycor.
    employee_id: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeId')

    # Employee's organization description
    employee_department_description: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeDepartmentDescription')

    # Employee's organization code
    employee_department_code: typing.Optional[typing.Optional[int]] = Field(None, alias='EmployeeDepartmentCode')

    # Employee's last name
    employee_last_name: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeLastName')

    # Employee's first name
    employee_first_name: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeFirstName')

    # Employee's middle name
    employee_middle_name: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeMiddleName')

    # Unique number of the employee in the tenant. Generated by Paycor.
    employee_number: typing.Optional[typing.Optional[int]] = Field(None, alias='EmployeeNumber')

    employee_status: typing.Optional[EmploymentStatus] = Field(None, alias='EmployeeStatus')

    # Check number.
    check_number: typing.Optional[typing.Optional[int]] = Field(None, alias='CheckNumber')

    # Period start date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
    period_start_date: typing.Optional[datetime] = Field(None, alias='PeriodStartDate')

    # Period end date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
    period_end_date: typing.Optional[datetime] = Field(None, alias='PeriodEndDate')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
