# coding: utf-8

"""
    Paycor Public API

     Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section.   # Getting Started  <strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>  # GET, PUT, POST  * When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc].  * When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system. * When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'   # Error Handling  * 400: Please consult the response text to correct your request information.  * 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key.  * 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header. * 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen.  * 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state.  * 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.   * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs).  * 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.   # IDs  * ClientId = LegalEntityId * TenantId = CompanyId * EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API  # Earnings, Deductions, Taxes  This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints.   Paycor stores Earnings, Deductions, and Taxes each at three levels: * Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):   * Earnings: REG, OT   * Taxes: FITWH, SOC, SOCER, OHCIN   * Deductions: 401k, KMat, H125, UWay * Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code.    * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints.  * Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code   * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden.   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paycor_python_sdk.pydantic.pay_frequency import PayFrequency
from paycor_python_sdk.pydantic.resource_reference import ResourceReference

class LegalEntityEarning(BaseModel):
    # Unique identifier of the legal entity's earning in Paycor's system. Generated by Paycor.
    id: typing.Optional[str] = Field(None, alias='Id')

    # Descriptive legal entity earning identifier set at the legal entity or tenant level.
    code: typing.Optional[typing.Optional[str]] = Field(None, alias='Code')

    # Global descriptive legal entity earning identifier.
    global_earning_code: typing.Optional[typing.Optional[str]] = Field(None, alias='GlobalEarningCode')

    # Description of the legal entity's earning code.
    description: typing.Optional[typing.Optional[str]] = Field(None, alias='Description')

    # Total hours worked for legal entity's earning.
    hours: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='Hours')

    # Fixed, recurring dollar amount.             
    amount: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='Amount')

    # Percentage value set by the user.             
    rate: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='Rate')

    frequency: typing.Optional[PayFrequency] = Field(None, alias='Frequency')

    # Whether legal entity's earning shows up on a W-2 tax form.             
    is_on_w2: typing.Optional[bool] = Field(None, alias='IsOnW2')

    # Whether legal entity's earning should appear on paychecks.             
    on_hold: typing.Optional[bool] = Field(None, alias='OnHold')

    # Date the legal entity earning take effect. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
    effective_start_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='EffectiveStartDate')

    # Value set by the user to multiply with the rate.             
    factor: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='Factor')

    legal_entity: typing.Optional[ResourceReference] = Field(None, alias='LegalEntity')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
